### ISSUE TITLE
 [AccountEligibility] Edit count rules are crosswiki by default

### ISSUE THREAD

**Issue by Steinsplitter** [Pathoschild/Wikimedia-contrib#85]
https://tools.wmflabs.org/meta/accounteligibility/42/Santamarcanda?
 • has at least 75 edits as of 31 December 2016 (has 82 so far).

But the user has less edits:
```
MariaDB [commonswiki_p]> SELECT COUNT(rev_id) FROM revision_userindex WHERE rev_user="6215773" AND rev_timestamp < "201701"
    -> ;
+---------------+
| COUNT(rev_id) |
+---------------+
|            25 |
+---------------+
1 row in set (0.01 sec)
```

**Comment by AntiCompositeNumber** [comment]
This issue only happens when using the auto-detect wiki function. Manually selecting Commons results in the correct number: https://tools.wmflabs.org/meta/accounteligibility/42/Santamarcanda?wiki=commonswiki

**Comment by Pathoschild** [comment]
Edits are accumulating crosswiki by default after the accounteligiblity rewrite. I'll fix that later today, once I make sure none of the event rules depend on that.

**Comment by Pathoschild** [comment]
Fixed and deployed. Can you confirm the results match what you expect now?

**Comment by sivaraam** [comment]
I guess this isn't fixed yet. I could see that the edit count is higher when analysis is done using the _auto-select wiki_ feature. See below links,
1. **Without** auto-select wiki feature : The  original edit-count for metawiki is `16` https://tools.wmflabs.org/meta/accounteligibility/44/Kaartic?wiki=metawiki
2. **With** auto-select wiki feature : The edit count for metawiki is shown as `309` (making that pass the condition falsly)
https://tools.wmflabs.org/meta/accounteligibility/44/Kaartic?

**Comment by Pathoschild** [comment]
@sivaraam That's normal: edits are supposed to be counted crosswiki for the 2017 Wikimedia Foundation elections. The bug happened when they were counted crosswiki even for events where they weren't supposed to be. :)
